Update text-effectCity-change.xml
BadaTheBada/OW_RussianPatch pull request #32
Opened 2020-06-20 16:52 UTC by AlexRjg

Сомения на строках:
1147-1163, 1308

2020-06-20 19:07 UTC, BadaTheBada requested changes
Отметила правки

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Мифологический Монастырь</Translation>
Монастырь Мифологии? Как с остальными теологиями

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Pleased (Религия)</Translation>
Перевести Pleased

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Культ меча</Translation>
"Меча" с прописной буквы, либо в остальных местах со строчной

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Проводить ежегодный праздник для Персидских гостей</Translation>
"Персидских" правильно со строчной буквы.
Можно "ежегодный" с прописной.
И мб "провести"?

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Зерновая Доля</Translation>
"Доля" со строчной

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Чужеземные Воины</Translation>
"Воины" со строчной

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Военный Совет</Translation>
"Совет" со строчной

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Драгоценный камень</Translation>
Ресурсы либо неисчисляемые (сыпучие, жидкие, кусковые), либо во множеством числе. Поэтому "драгоценные камни"

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Лошадь</Translation>
Лошади

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Верблюд</Translation>
Верблюды

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Слон</Translation>
Слоны

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Пряность</Translation>
Пряности

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Оливка</Translation>
Оливки

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Краска</Translation>
Красители

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Жемчужина</Translation>
Жемчуг

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Оратор Leader</Translation>
Правитель Оратор?

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Судья Leader</Translation>
Правитель Судья?

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Строитель Leader</Translation>
Правитель Строитель?

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Командир Leader</Translation>
Правитель Командир?

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Фанатик Leader</Translation>
Правитель Фанатик?

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Вдохновленный</Translation>
Вдохновляющий

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Безнравственный</Translation>
Продажный, как ты предложил

2020-06-20 19:07 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Гнездо</Translation>
Оплот

2020-06-20 19:11 UTC, supoved commented on Russian/text-effectCity-change.xml
> +		<Translation>Проводить ежегодный праздник для Персидских гостей</Translation>
Т.к. он ежегодный, не сочетается с "провести"(один раз)
Можно использовать "организовать", ибо "проводить" режет глаз и слух

2020-06-20 19:17 UTC, supoved commented on Russian/text-effectCity-change.xml
> +		<Translation>Командир Leader</Translation>
"Военноначальник" имхо, или хотябы "Командующий"

2020-06-20 19:18 UTC, supoved commented on Russian/text-effectCity-change.xml
> +		<Translation>Фанатик Leader</Translation>
zealot - a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.
имхо "Фанатичный правитель"/"Бескомпромиссный правитель"

2020-06-20 19:35 UTC, BadaTheBada commented on Russian/text-effectCity-change.xml
> +		<Translation>Проводить ежегодный праздник для Персидских гостей</Translation>
У тебя каждый ход - новый год) Если это выбираемое действие (как, например, фестиваль), то "провести в этом году" кажется вполне себе вариантом

2020-06-21 08:50 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Командир Leader</Translation>
я оставлю командир. когда в trait поменяется, поменяю и здесь

2020-06-21 08:53 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Фанатик Leader</Translation>
то же самое. согласно файлу trait

2020-06-21 08:54 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Вдохновленный</Translation>
брал из trait

2020-06-21 08:54 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Безнравственный</Translation>
OK

2020-06-21 08:54 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Гнездо</Translation>
OK

2020-06-21 09:03 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Зерновая Доля</Translation>
Кто переводил text-project-event-change? там с заглавной
строка 91
		<zType>TEXT_PROJECT_GRAIN_DOLE</zType>
		<Translation>Зерновая Доля</Translation>

2020-06-21 09:04 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Чужеземные Воины</Translation>
text-project-event-change:	
<zType>TEXT_PROJECT_FOREIGN_FIGHTERS</zType>
		<Translation>Чужеземные Воины</Translation>

2020-06-21 09:05 UTC, AlexRjg commented on Russian/text-effectCity-change.xml
> +		<Translation>Драгоценный камень</Translation>
см выше

2020-06-21 16:00 UTC, merged